-- 1. Exiba os dados da compra (item_ordem_compra) de todos os materiais cujo quantidade seja maior que 10.

SELECT
	IOC.IDORDEMCOMPRA ,
	IOC.QUANTIDADE ,
	IOC.VALOR ,
	M.NOME
FROM
	ITEM_ORDEM_COMPRA IOC
JOIN MATERIAL M ON 
IOC.IDORDEMCOMPRA = M.ID 
WHERE
	IOC.QUANTIDADE > 10
ORDER BY
	IOC.QUANTIDADE ASC;

-- 2. Exiba os dados da compra (item_ordem_compra) de todos os materiais cujo valor seja menor que 50.


SELECT
	IOC.IDORDEMCOMPRA ,
	IOC.QUANTIDADE ,
	IOC.VALOR ,
	M.NOME
FROM
	ITEM_ORDEM_COMPRA IOC
JOIN MATERIAL M ON 
IOC.IDORDEMCOMPRA = M.ID 
WHERE
	IOC.VALOR < 50
ORDER BY
	IOC.VALOR DESC ;

-- (ambas) 

SELECT
	IOC.IDORDEMCOMPRA ,
	IOC.QUANTIDADE ,
	IOC.VALOR ,
	M.NOME
FROM
	ITEM_ORDEM_COMPRA IOC
JOIN MATERIAL M ON 
IOC.IDORDEMCOMPRA = M.ID 
WHERE
 IOC.QUANTIDADE > 10 AND 
 IOC.VALOR < 50
ORDER BY
	IOC.QUANTIDADE ASC ;

--3 Exibir os dados da compra de todos os materiais cuja quantidade seja maior que 100 e o valor seja menor que 50, contendo o nome do material e o nome do fornecedor. 

SELECT
	IDORDEMCOMPRA ,
	IDMATERIAL ,
	IOC.QUANTIDADE ,
	IOC.VALOR,
	F.NOME AS 'FORNECEDOR',
	M.NOME AS 'MATERIAL'
FROM
	ITEM_ORDEM_COMPRA IOC
JOIN ORDEM_COMPRA OC ON
	IOC.IDORDEMCOMPRA = OC.ID
JOIN MATERIAL M ON
	IOC.IDMATERIAL = M.ID 
JOIN FORNECEDOR F ON
	OC.IDFORNECEDOR = F.ID
	WHERE IOC.QUANTIDADE > 100 AND IOC.VALOR < 50
	ORDER BY IOC.QUANTIDADE ASC;

--4. Exiba o subtotal de cada material vendido, o nome do material e o nome do fornecedor para cada item de compra.

SELECT
	IOC.IDORDEMCOMPRA ,
	IOC.IDMATERIAL ,
	IOC.QUANTIDADE ,
	IOC.VALOR,
	M.NOME AS 'MATERIAL',
	F.NOME AS 'FORNECEDOR',
	QUANTIDADE * VALOR AS SUBTOTAL
FROM
	ITEM_ORDEM_COMPRA IOC
JOIN MATERIAL M ON
	IOC.IDMATERIAL = M.ID
JOIN ORDEM_COMPRA OC ON
	IOC.IDORDEMCOMPRA = OC.ID
JOIN FORNECEDOR F ON
	OC.IDFORNECEDOR = F.ID;

-- 5. O nome do fornecedor da ordem de compra, a ordem de compra e o total pago pela ordem de compra.

SELECT
	F.NOME,
	OC.ID,
	SUM(IOC.QUANTIDADE * IOC.VALOR) AS 'TOTAL ORDEM DE COMPRA'
FROM
	ORDEM_COMPRA OC
JOIN ITEM_ORDEM_COMPRA IOC ON
	OC.ID = IOC.IDORDEMCOMPRA
JOIN FORNECEDOR F ON
	OC.IDFORNECEDOR = F.ID
GROUP BY
	IOC.IDORDEMCOMPRA
	ORDER BY IOC.IDORDEMCOMPRA ASC;


-- 6. O nome do fornecedor da ordem de compra, a data da ordem de compra, o total pago pela ordem de compra, num determinado intervalo de datas.

SELECT
	F.NOME,
	OC.DATA,
	SUM(IOC.QUANTIDADE * IOC.VALOR) AS 'TOTAL ORDEM DE COMPRA'
FROM
	ORDEM_COMPRA OC
JOIN ITEM_ORDEM_COMPRA IOC ON
	OC.ID = IOC.IDORDEMCOMPRA
JOIN FORNECEDOR F ON
	OC.IDFORNECEDOR = F.ID
GROUP BY
	IOC.IDORDEMCOMPRA
HAVING 
	OC.DATA BETWEEN '2022-05-15' AND '2022-05-20' 
	ORDER BY IOC.IDORDEMCOMPRA ASC;




