--1. Listar o nome de cada material e o valor médio desse material

SELECT
	M.NOME AS 'MATERIAL',
	AVG (VALOR) AS 'MÉDIA DE VALOR VENDA'
FROM
	ITEM_ORDEM_COMPRA IOC
JOIN MATERIAL M ON
	IOC.IDMATERIAL = M.ID
GROUP BY
	M.ID
ORDER BY
	M.NOME ASC;

--2. Listar o nome de cada material e o valor médio desse material entre os dias 10/05/2022 e 13/05/2022
SELECT
	M.NOME AS 'MATERIAL',
	AVG (VALOR) AS 'MÉDIA DE VALOR VENDA'
FROM
	ITEM_ORDEM_COMPRA IOC
JOIN MATERIAL M ON
	IOC.IDMATERIAL = M.ID
JOIN ORDEM_COMPRA OC ON
	IOC.IDORDEMCOMPRA = OC.ID
WHERE
	OC.DATA BETWEEN '2022-05-10' AND '2022-05-13'
GROUP BY
	M.ID
ORDER BY
	M.NOME ASC;

--3. Qual é o produto que mais aparece nas compras?

SELECT
	M.ID AS 'ID',
	M.NOME AS 'MATERIAL',
	COUNT(IDMATERIAL) AS 'CONTAGEM'
FROM
	ITEM_ORDEM_COMPRA IOC
JOIN MATERIAL M ON
	IOC.IDMATERIAL = M.ID
GROUP BY
	M.ID
ORDER BY
	 CONTAGEM DESC;
